language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

before_install:
  - sudo apt-get update
  - source .travis/setenv_lua.sh
  - bash .travis/install_rocks.sh
  - bash .travis/install_rote.sh
  - sudo apt-get install valgrind
  - sudo pip install cpp-coveralls

script:
  - bash .travis/test_with_valgrind.sh
  - bash .travis/c_coverage.sh

after_success:
  - coveralls -b . --dump c.report.json
  - luacov-coveralls -j c.report.json -v
